#gomarkdoc -v ./parser -o DOKUMENTATION.md
output:
  file: "DOCUMENTATION.md"
  format: "markdown"
  mode: "replace"
  
header: |
  Due to breaking changes in the `osu!.db` introduced in version `20250107`, have outdated types been suffixed with `Old`. These outdated types will only be populated when the version is *below* the aforementioned one.

  For more details check the official [Documentation](https://github.com/ppy/osu/wiki/Legacy-database-file-structure#osudb)

repository:
  url: "https://github.com/juli0n21/go-osu-parser"
  defaultBranch: "main"
  path: ""

filters:
  include: ["parser/*.go"]
