name: Generate and Push Go Documentation on Tag

on:
  push:
    tags:
      - '*'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  

    - name: Set up Go environment
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.5'

    - name: Install gomarkdoc
      run: |
        go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

    - name: Generate Go documentation
      run: |
        gomarkdoc -v ./parser -o DOKUMENTATION.md

    - name: Commit generated documentation
      run: |
        git add README.md
        git commit -m "Add generated Go documentation"
        git push --set-upstream origin $GITHUB_REF

    - name: Push changes
      run: |
        git push --force
